[project]
name = "sumnplot"
version = "0.5.0.dev0"
description = "Super simple summarisation and plotting."
readme = "README.md"
authors = [
    { name = "Richard Angell", email = "richardangell37@gmail.com" }
]
homepage = "https://github.com/richardangell/sumnplot"
repository = "https://github.com/richardangell/sumnplot"
documentation = "https://sumnplot.readthedocs.io/en/latest/"
requires-python = ">=3.12"
dependencies = [
    "altair>=6.2.2",
    "matplotlib>=3.9.2",
    "pandas>=3.0.5",
    "polars>=1.43.2",
    "scikit-learn>=1.5.0",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
    "prek>=0.4.12",
    "pyrefly>=1.2.0",
    "pytest>=9.1.1",
]
docs = [
    "sphinx>=9.1.0",
    "sphinx-rtd-theme>=3.1.0",
]

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

target-version = "py314"

[tool.ruff.lint]
select = [
    "E",     # pycodestyle
    "F",     # Pyflakes
    "I",     # isort
    "N",     # pep8-naming
    "RUF",   # Ruff-specific rules
    "TRY",   # tryceratops
    "ERA",   # eradicate
    "D",     # pydocstyle
    "A",     # flake8-builtins
    "ANN",   # flake8-annotations
    "ARG",   # flake8-unused-arguments
    "ASYNC", # flake8-async
    "B",     # flake8-bugbear
    "BLE",   # flake8-blind-except
    "C4",    # flake8-comprehensions
    "COM",   # flake8-commas
    "DTZ",   # flake8-datetimez
    "EM",    # flake8-errmsg
    "FA",    # flake8-future-annotations
    "FBT",   # flake8-boolean-trap
    "G",     # flake8-logging-format
    "ICN",   # flake8-import-conventions
    "INP",   # flake8-no-pep420
    "ISC",   # flake8-implicit-str-concat
    "LOG",   # flake8-logging
    "PIE",   # flake8-pie
    "PT",    # flake8-pytest-style
    "PTH",   # flake8-use-pathlib
    "RET",   # flake8-return
    "S",     # flake8-bandit
    "SIM",   # flake8-simplify
    "SLF",   # flake8-self
    "TC",    # flake8-type-checking
    "TD",    # flake8-todos
    "YTT",   # flake8-2020
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = [
    "S101",    # use of assert
    "D104",    # missing docstring in public package
    "ANN201",  # missing return type for public function
    "INP001",  # implicit namespace package
    "TC002",   # move import to type-checking block
    "TC003",   # move import to type-checking block
]
