# This workflow will install the package and dependencies, lint and run bandit
# with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "flit>=3.2,<4"
        flit install --deps=all

    - name: Lint with flake8
      if: always()    
      run: |
        flake8 .

    - name: mypy
      if: always()    
      run: |
        mypy src/sumnplot/ --ignore-missing-imports --scripts-are-modules

    - name: Lint with black
      if: always()    
      run: |
        black --version
        black --check .

    - name: Run Bandit tests
      if: always()
      run: |
        bandit -r src/sumnplot -f html -o bandit-test-results.html

    - name: Upload bandit test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: bandit-results
        path: bandit-test-results.html